### ISSUE TITLE
Improve pipelines save

### ISSUE THREAD

**Issue by dhrbn** [populse/capsul#114]
Hi everyone,

I would like to add some code to improve the save of the pipelines, to save_py_pipeline and save_xml_pipeline more precisely (I work with PipelineDevelopperView):

- In save_py_pipeline:
	- Saving all plug values. The current function, if I am not mistaken, only allow to write the pipeline inputs and outputs. I would like to parse all the nodes and add "        self.nodes[node_name].set_plug_value(plug_name, value)" to the saved .py file.

- In save_xml_pipeline:
	- Debugging the case when the doc is empty. 
The saved xml file contains "`...<doc /><process...`"  and creates a bug when loading the pipeline:
File "/usr/local/lib/python3.5/dist-packages/capsul-2.1.3-py3.5.egg/capsul/pipeline/xml.py", line 65, in create_xml_pipeline
    builder.set_documentation(child.text.strip())
AttributeError: 'NoneType' object has no attribute 'strip'
So I have to change each xml file as this: "`...<doc>AnyText</doc><process...`" for the moment

- Somewhere in PipelineDevelopperView
	- Debugging the GUI when an xml pipeline is loaded. When loading a valid xml file, the GUI does not behave as we could expect (cf. screenshot) but it does not affect the pipeline (it can be run correctly).

If it's ok for you I can work on these three things next week and make a pull request! Please tell me what you think!

![screenshot_loaded_xml_pipeline](https://user-images.githubusercontent.com/37616080/40548310-a63846a2-6034-11e8-9681-aa4989f6a8ee.png)

**Comment by denisri** [comment]
Points 2 and 3 are probably "just" bugs, 2 seems easy (it just lacks a test for empty elements), I haven't looked at 3 but there will be a way to fix it). The real discussion is on point 1, which is actually a non-trivial question.
On the purpose: saving pipelines with full parameters set, I totally agree that this will be needed to save/reload things, and to record runs history.
However I wonder if we should not try (or at least allow) to keep things separated:
* The pipeline structure (and maybe default parameters) is a reusable process that can be included afterwards in other, larger pipelines.
* The full parameters set is specific to one run and does not need to be saved with the pipeline structure - even maybe should not be, because they would overwrite non-filled parameters and would bring confusions end errors.
And it's not always so easy to decide if a value is a `default` value or a specific value assigned for one run, so the separation between the two aspects is not obvious for the pipeline editor tool.

Now there are tools to help saving or retreiving parameters for a pipeline: see `capsul.pipeline.pipeline_tools.dump_pipeline_state_as_dict()` and `capsul.pipeline.pipeline_tools.set_pipeline_state_from_dict()`.

The above functions should get/set the entire state of a pipeline with its childen nodes (I don't swear that there are no missing things right now but it can be improved otherwise).

However after we have done this, we got the impression that most of it (the children state parsing) should normally be useless since we can postulate that a "good pipeline" should expose all its needed parameters (including switch states etc) to its external parameters set: in other words, a pipeline has to be a black box in order to be usable as a regular process inside another pipeline, and we should not access its internals when they are not exported to the outer world.

**Comment by dhrbn** [comment]
Thank you for your answer! I totally agree with you on the fact that there have to be two kinds of parameters, depending on if they are specific to the pipeline global inputs or not and the limit between them may be not easy to set up.

Maybe should we organize a meeting in the next days, what do you think? This week I'm available until Thursday morning.

**Comment by denisri** [comment]
I could find a bit of time on tuesday or wednesday, not on thursday or friday.

**Comment by dhrbn** [comment]
It's ok for us! Just tell us what time slots is the best for both of you (@denisri and @sapetnioc )

**Comment by sapetnioc** [comment]
Sorry I did not see this messages before. We are available today David to
discuss this topic. What about now ?

**Comment by dhrbn** [comment]
No problem! It's ok for us, let's say in 15 minutes!

**Comment by denisri** [comment]
OK.

**Comment by dhrbn** [comment]
Further to our meeting yesterday, I have added some code to MIA's pipeline_developper_view.py to load and save pipeline parameters with a Json file (cf. https://github.com/populse/populse_sandbox/blob/c4ed7c91bb2596a9c4046b4afee829edfe01e197/python/populse_mia/src/modules/PipelineManager/CAPSUL_Files/pipeline_developper_view.py#L3306). 

Some rapid tests have been made, I should go further on them next week, but the code seems ok. After that should I add the core of the code in two functions in Capsul's pipeline_tools.py ? 

Moreover, do we only save the pipeline's input/output or should we save some other information? (I have not saved the nodes_activation trait, should I too?)

**Comment by denisri** [comment]
I have just pushed a series of fixes which include:
* fixed NiPype interfaces IO
* save non-default internal values in pipeline nodes
* other IO issues (both python and XML), added a test for them
* fixed the empty doc issue in xml

For the pipeline view issue, I think it is the new mode which hides optional parameters which also hides connections to hidden plugs. This makes me think that this view is not OK in this state since it makes things confused instead of showing clearly the pipeline structure...

**Comment by denisri** [comment]
I think this issue is fixed. If not please reopen.
