### ISSUE TITLE
we need to have a lock system for process parameters during completion

### ISSUE THREAD

**Issue by denisri** [populse/capsul#170]
Parameters set manually by the user should not be changed by the completion system. However right now we have no reliable way to know whether a parameter has been set manually (thus "locked") or not.
Maybe using a "locked" attribute on the trait ? - but this would not be persistant when the process parameters are saved.

**Comment by denisri** [comment]
or a trait in Process holding a list of modified / locked parameters ?

**Comment by servoz** [comment]
I don't know if I'm off topic but currently for mia_processes this is managed during initialization, in the list_outputs method. It works with a test like

```
if (self.theParamter is Undefined):
    doAutoCompletion

```
It's a flexible way because it allows you to choose for each brick (process) if you want the user to be able to change the settings or not.

**Comment by denisri** [comment]
Currently there is a test like this in the initialization code, yes, but it's not enough: default values are not always `Undefined`, but could be any value - with various types (booleans, strings, lists etc). In populse/populse_mia#167 I also test if the values are equal to traits defaults, but this is also not enough: once a pipeline has been initialized (and maybe run) once, many values are not default ones any longer, but the user still might change manally some values and initialize/run again. And here we cannot know which values have actually been modified by the user (thus should not be changed during init) or been set by the init/completion system for the previous execution (in which case a new init should maybe change them).

**Comment by servoz** [comment]
Okay, I understand the problem. Thank you!

**Comment by denisri** [comment]
If no objection is raised I will implement it as a list of locked parameters as an additional trait in the `Process` class, rather than a trait attribute, because it's more a value than a process trait definition.

**Comment by denisri** [comment]
This additional "parameter" would be set by the GUI (ControllerWidget) when a value is edited. Thus I wonder if the locking system should not be implemented at lower level, in `Controller` ?

**Comment by servoz** [comment]
I don't see objection for this.

**Comment by sapetnioc** [comment]
I agree to put parameters with non default values (I would call them
"protected" parameters values) in a, possibly hidden, trait. This way, this
information will always be stored with the pipeline. And it is good because
it is part of the state of the pipeline. For the low level implementation
of the parameter protection system I think the main point is to decide what
to do by default when setting a process parameter value : either protect
the parameter (i.e. remove its "defaultness", preventing it to be modified
automatically) or not. Both can be interesting but to keep things simple by
default, I am in favor of doing nothing by default and to add a specific
method (or boolean parameter) to set a protected value.

**Comment by denisri** [comment]
If you prefer "protected" to "locked", it's fine for me :)
I also prefer not changing the default behavior of seattr() because values will not always be changed by users.
However the link system in pipelines (propagating a value from a node to another) should propagate the protected status of parameters, otherwise they will not be actually protected.
