### ISSUE TITLE
New modules API

### ISSUE THREAD

**Issue by sapetnioc** [populse/capsul#208]
I new API, the configuration of Capsul execution environmenent must support modules. For instance configuration of external software would use modules. This issue is the place to track the development of modules related features.

**Comment by denisri** [comment]
This topic is closely related to the configuration API and storage.
The current API (done in #145 a couple of years ago) has modules, requests, and multiple-configurations support.
However the config deserves a refactoring, in my optinion for 2 reasons:
* it currently needs a database and populse_db, which is probably a bit overkill for "just" configuration definition. The database is somewhat hidden in the implementation, thus this points could be more an implementation rework than an API redesign, and it is not an urgent matter as we can decide to change the implementation later.
* its API is a bit too complex and "heavy" I think: for instance to set a config option we have to write multiple lines of code, such as:
  ```
  with engine.settings as session:
      conf = session.config('freesurfer', environment)
            values = {'config_id': 'freesurfer',
                      'subjects_dir': fs_directory,
                      'setup': fs_setup_script}
            if conf is None:
                session.new_config('freesurfer', environment, values)
            else:
                for k, value in values.items():
                    if k == 'config_id':
                        continue
                    setattr(conf, k, values[k])
  ```
  which is a little bit crazy, when you think ;)

We thus need either to redesign completely the config API, or at least write some helper functions to help setting/getting simple config options.
It should be noted that we need that in both master and the new branches (pydantic_controller) because the removal/replacement of the old `StudyConfig` is heavily slowed by the burden of the current config API, actually. Many codes are still using `StudyConfig` just because it was way simpler to use: `study_config.option = value` was quite more convenient than the 12 lines of code above (but it was insufficient for multiple configs, sure).
The modules system may stay the same as today, I don't see major drawbacks with it.
