### ISSUE TITLE
capsul.process.Process.check_requirements() return

### ISSUE THREAD

**Issue by servoz** [populse/capsul#280]
To take an example, let's say we use a pipeline with two processes:
- one from SPM (mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth())
- and one coming from FSL (mia_processes.bricks.preprocess.fsl.processes.Smooth())

If we use the Process.check_requirements() method for each of these bricks, this is what is returned:
- The configuration for SPM and FSL are well set:
  For the SPM process:
```
{'capsul_engine':
         {'uses':
             {'capsul.engine.module.nipype': 'any',
              'capsul.engine.module.spm': 'any',
              'capsul.engine.module.matlab': 'any'
             }
         },
  'capsul.engine.module.nipype':
         {'config_id': 'nipype',
          'config_environment': 'global'
         },
  'capsul.engine.module.spm':
         {'config_id': 'spm-standalone',
          'config_environment': 'global',
          'directory': '/home/econdami/SPM/spm12',
          'standalone': False
         },
  'capsul.engine.module.matlab':
         {'config_id': 'matlab',
          'config_environment': 'global',
          'executable': '/home/econdami/MATLAB/R2018b/bin/matlab',
          'mcr_directory': '/home/econdami/MATLAB/MATLAB_Runtime/v95'
         }
}
```
 For the FSL process:
```
{'capsul_engine':
         {'uses':
             {'capsul.engine.module.nipype': 'any',
              'capsul.engine.module.fsl': 'any'
             }
         },
 'capsul.engine.module.nipype':
         {'config_id': 'nipype',
          'config_environment': 'global'
         },
 'capsul.engine.module.fsl':
         {'config_id': 'fsl',
          'config_environment': 'global',
          'directory': '/data_2/fsl',
          'config': '/data_2/fsl/etc/fslconf/fsl.sh'
         }
}
```
This result is expected.

- The configuration for SPM and FSL are not set:
  For the SPM process:
  `None`
  For the FSL process:
```
{'capsul_engine':
         {'uses':
             {'capsul.engine.module.nipype': 'any',
              'capsul.engine.module.fsl': 'any'
             }
         },
 'capsul.engine.module.nipype':
         {'config_id': 'nipype',
          'config_environment': 'global'
         },
 'capsul.engine.module.fsl':
         {'config_id': 'fsl',
          'config_environment': 'global'
         }
}
```

For FLS, I can understand the result.

For SPM is it possible to get the uses value (actually the requirement requested by the process) ? and no module because the requirement is not met. Something like this:
```
{'capsul_engine':
         {'uses':
             {'capsul.engine.module.nipype': 'any',
              'capsul.engine.module.spm': 'any',
              'capsul.engine.module.matlab': 'any'
             }
         }
}
```

This would allow us to use the result of Process.check_requirements() directly in Mia.

**Comment by denisri** [comment]
Yes, there is a discrepency between FSL and SPM, and `check_requirements()` doesn't fully do its job.

But I think you are not expecting the right thing from `check_requirements()`: its job is not to provide which config options should be filled, but to say if the config values are OK to run the job. Here the answer is **NO**.
So it's not SPM which is wrong, but FSL. Here you don't have filled the config: it is not valid, so `check_requirements()` should return `None`.

> For SPM is it possible to get the uses value (actually the requirement requested by the process) ? and no module because the requirement is not met. 

I don't understand what you are expecting: is this not `process.requirements()` ?
Or you mean requirements _with dependencies_ ? Yes I think I understand. OK then it's:
```
engine.settings.select_configurations('global', uses=process.requirements())['capsul_engine']['uses']
```

What I propose is to add a function in each config module to check if the selected config is obviously invalid (for instance if a mandatory path is left to `Undefined`). `Settings.select_configurations()` would (maybe optionally) check the configs it selects using this function, and discard them if the check is not passed.
This way, process.check_requirements() would return `None` in both cases (SPM and FSL), and this would be right.
Note that more information is given by check_requirements() if an optional list of messages is provided:
```
msg = []
res = process.check_requirements('global', msg)
if res is None:
    print('requirements failed because:')
    print(msg)
```
currently there is a bug in those messages, they print the full requirements dict instead of just the unmet required modules, I'm fixing it.
Would this be OK ?

**Comment by servoz** [comment]
I just see your c545423 commit. I will see what can I do with it!
Thanks!

**Comment by denisri** [comment]
Paths validity is complex in a client/server environment, so yes we should postpone this topic, and focus on the existence of values in paths.
I'm writing a bit of code to check that. Each module can provide a check function.

**Comment by servoz** [comment]
For me it's OK.
I managed to do what needed to be done in populse_mia with the requirements (or rather lack of them).
It is obvious that this is only a first superficial layer (but necessary), because one day it will be necessary to test the config at runtime (for remote calculations) and the use of environment variables ( if the config is not filled in and the environment variable has been defined by the user).
I opened a [PR](https://github.com/populse/capsul/pull/281) in connection with this ticket (in order to avoid producing side effects which I would not have thought of). This [PR](https://github.com/populse/capsul/pull/281) is necessary for things to work properly.
In nutshell:
- we always add matlab when we need spm (not only for spm standalone)
- In spm validity check the version can be undefined
- A small minor modification to space out the printing of the configurations if there are several.
