### ISSUE TITLE
tests on populse_mia are currently failing

### ISSUE THREAD

**Issue by servoz** [populse/capsul#283]
and only for the windows build ... (fine with linux and mac) .
```
======================================================================
ERROR: test_z_init_pipeline (__main__.TestMIAPipelineManagerTab)
Adds a process, mocks several parameters from the pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\\python\\populse_mia\\test.py", line 10286, in test_z_init_pipeline
  File "C:\projects\populse-mia\python\populse_mia\user_interface\pipeline_manager\pipeline_manager_tab.py", line 1670, in init_pipeline
    print(study_config.engine.settings.select_configurations("global"))
  File "C:\projects\capsul\capsul\engine\settings.py", line 191, in select_configurations
    len(docs), module))
OSError: Cannot create configurations for environment "global" because settings returned 2 instances for module capsul.engine.module.spm

```
it seems to be from commit 153dab3 (fine with  8179433).

To fix this problem I'll have to use RDP from a windows virtual machine .... to see what's going on in the appveyor build ... If there is an obvious idea following changes in capsul, I'm interested !!!!

**Comment by denisri** [comment]
The capsul `StudyConfig` was missing something for a SPM standalone config with a MCR directory not inside the SPM directory. As the SPM install in our lab has recently changed in this way, I had to fix it quickly, but I have likely not done it the right way. I decided to use the `spm_directory` to rather represent the MCR directory (because there was no place it was configured, and `spm_directory` was containing info already in `spm_executable`), but doing this I changed the meaning of `spm_directory`, which is not right, and some code is not expecting that. I have to redo it a better way.
I's a bit a mess because we are changing `StudyConfig` here, which is obsolete and is supposed not to be maintained any longer, then we must maintain sync with `CapsulEngine`, then with Axon config, and Populse MIA config... In other words it's probably going to take me the day to fix it in an obsolete and unmaintained API... well it's life...

**Comment by servoz** [comment]
Okay, I see and I sympathize!

But apart from that, I'm very surprised that the tests only crash for Windows in this case... Do you have any idea? If not, never mind!

Anyway, thanks for letting me know because I was about to start introspection in the windows build appveyor (which is always a pain!) ... for nothing!

Let me know when it's fixed on your end and I'll restart the populse_mia unit tests.

**Comment by servoz** [comment]
for populse_mia don't hesitate to let me know if I can help ... !

**Comment by denisri** [comment]
No, no idea why it fails only on windows. But our linux tests for Morphologist are also broken, so I hope fixing them (correctly this time!) will also fix your problem.

**Comment by denisri** [comment]
I have reworked the SPM config in master branch. Tests in brainvisa have not completely run however (because the test machine has been reinstalled with a new system) so I can't guarantee that it is OK (but manual tests did pass on linux for capsul and morphologist). But I'm not sure it will fix your issue either. If you could give it a try and tell me if anything has changed ?
I have not backported to branch brainvisa-5.1 yet because I want to make sure it is OK in master, first.

**Comment by denisri** [comment]
So the problem here is probably not related to my last fix. It seems related to 153dab346f3e8ea1b8635ed0739f986922973973 as you have noted, since this change removes the requirement `"spm": "any'` (because the FOM module does not depend on the spm module), but here, by doing this, it also removes the selection ("`any`" means the first matching config, while here we have 2).
The real problems are thus:
- why de we have 2 distinct configs for SPM here only in Windows
- if no requirement would select spm, this config ambiguity should not cause an error - maybe this is the key point.

**Comment by denisri** [comment]
The error raises "just" because of a print:
```
  File "C:\projects\populse-mia\python\populse_mia\user_interface\pipeline_manager\pipeline_manager_tab.py", line 1670, in init_pipeline
    print(study_config.engine.settings.select_configurations("global"))
```
and `engine.settings.select_configurations("global")` actually performs a selection where each module config should be unique, whereas we have two here. The code in the print shoud rather be replaced with:
```
    print(study_config.engine.settings.export_config_dict("global"))
```
`export_config_dict` does not perform a selection. Of course in the long run, the print should be removed.

The remaining question is: why do we have 2 configs for SPM on windows in this test, and only one on other platforms ?
